/*
 * declare_get_application_precursor.h
 *
 *  Created on: Dec 7, 2021
 *      Author: fehn
 */

#ifndef INCLUDE_EXADG_INCOMPRESSIBLE_NAVIER_STOKES_DECLARE_GET_APPLICATION_PRECURSOR_H_
#define INCLUDE_EXADG_INCOMPRESSIBLE_NAVIER_STOKES_DECLARE_GET_APPLICATION_PRECURSOR_H_



#endif /* INCLUDE_EXADG_INCOMPRESSIBLE_NAVIER_STOKES_DECLARE_GET_APPLICATION_PRECURSOR_H_ */
