var searchData=
[
  ['laplacekernel_127',['LaplaceKernel',['../classExaDG_1_1Poisson_1_1Operators_1_1LaplaceKernel.html',1,'ExaDG::Poisson::Operators']]],
  ['laplacekernel_3c_20dim_2c_20number_2c_20n_5fcomponents_20_3e_128',['LaplaceKernel&lt; dim, Number, n_components &gt;',['../classExaDG_1_1Poisson_1_1Operators_1_1LaplaceKernel.html',1,'ExaDG::Poisson::Operators']]],
  ['laplacekerneldata_129',['LaplaceKernelData',['../structExaDG_1_1Poisson_1_1Operators_1_1LaplaceKernelData.html',1,'ExaDG::Poisson::Operators']]],
  ['laplaceoperator_130',['LaplaceOperator',['../classExaDG_1_1Poisson_1_1LaplaceOperator.html',1,'ExaDG::Poisson']]],
  ['laplaceoperator_3c_20dim_2c_20number_2c_201_20_3e_131',['LaplaceOperator&lt; dim, Number, 1 &gt;',['../classExaDG_1_1Poisson_1_1LaplaceOperator.html',1,'ExaDG::Poisson']]],
  ['laplaceoperatordata_132',['LaplaceOperatorData',['../structExaDG_1_1Poisson_1_1LaplaceOperatorData.html',1,'ExaDG::Poisson']]],
  ['lazy_5fptr_133',['lazy_ptr',['../classExaDG_1_1lazy__ptr.html',1,'ExaDG']]],
  ['lazy_5fptr_3c_20affineconstraints_3c_20number_20_3e_20_3e_134',['lazy_ptr&lt; AffineConstraints&lt; Number &gt; &gt;',['../classExaDG_1_1lazy__ptr.html',1,'ExaDG']]],
  ['lazy_5fptr_3c_20matrixfree_3c_20dim_2c_20number_20_3e_20_3e_135',['lazy_ptr&lt; MatrixFree&lt; dim, Number &gt; &gt;',['../classExaDG_1_1lazy__ptr.html',1,'ExaDG']]],
  ['lazy_5fptr_3c_20vectortype_20_3e_136',['lazy_ptr&lt; VectorType &gt;',['../classExaDG_1_1lazy__ptr.html',1,'ExaDG']]],
  ['lbf_137',['lbf',['../classdealspectrum_1_1Bijection.html#a5db46c7927d7529fd683f5004bc96fab',1,'dealspectrum::Bijection']]],
  ['liftanddragcalculator_138',['LiftAndDragCalculator',['../classExaDG_1_1LiftAndDragCalculator.html',1,'ExaDG']]],
  ['liftanddragdata_139',['LiftAndDragData',['../structExaDG_1_1LiftAndDragData.html',1,'ExaDG']]],
  ['line_140',['Line',['../structExaDG_1_1IncNS_1_1Line.html',1,'ExaDG::IncNS']]],
  ['linearizedoperator_141',['LinearizedOperator',['../classExaDG_1_1Structure_1_1LinearizedOperator.html',1,'ExaDG::Structure']]],
  ['linearoperator_142',['LinearOperator',['../classExaDG_1_1Structure_1_1LinearOperator.html',1,'ExaDG::Structure']]],
  ['linearoperatorcoupled_143',['LinearOperatorCoupled',['../classExaDG_1_1IncNS_1_1LinearOperatorCoupled.html',1,'ExaDG::IncNS']]],
  ['linearoperatorcoupled_3c_20dim_2c_20double_20_3e_144',['LinearOperatorCoupled&lt; dim, double &gt;',['../classExaDG_1_1IncNS_1_1LinearOperatorCoupled.html',1,'ExaDG::IncNS']]],
  ['linecircumferentialaveraging_145',['LineCircumferentialAveraging',['../structExaDG_1_1IncNS_1_1LineCircumferentialAveraging.html',1,'ExaDG::IncNS']]],
  ['linehomogeneousaveraging_146',['LineHomogeneousAveraging',['../structExaDG_1_1IncNS_1_1LineHomogeneousAveraging.html',1,'ExaDG::IncNS']]],
  ['lineplotcalculator_147',['LinePlotCalculator',['../classExaDG_1_1IncNS_1_1LinePlotCalculator.html',1,'ExaDG::IncNS']]],
  ['lineplotcalculatorstatistics_148',['LinePlotCalculatorStatistics',['../classExaDG_1_1IncNS_1_1LinePlotCalculatorStatistics.html',1,'ExaDG::IncNS']]],
  ['lineplotcalculatorstatisticshomogeneous_149',['LinePlotCalculatorStatisticsHomogeneous',['../classExaDG_1_1IncNS_1_1LinePlotCalculatorStatisticsHomogeneous.html',1,'ExaDG::IncNS']]],
  ['lineplotdata_150',['LinePlotData',['../structExaDG_1_1IncNS_1_1LinePlotData.html',1,'ExaDG::IncNS']]],
  ['lineplotdatainstantaneous_151',['LinePlotDataInstantaneous',['../structExaDG_1_1IncNS_1_1LinePlotDataInstantaneous.html',1,'ExaDG::IncNS']]],
  ['lineplotdatastatistics_152',['LinePlotDataStatistics',['../structExaDG_1_1IncNS_1_1LinePlotDataStatistics.html',1,'ExaDG::IncNS']]],
  ['lowstoragerk3stage4reg2c_153',['LowStorageRK3Stage4Reg2C',['../classExaDG_1_1LowStorageRK3Stage4Reg2C.html',1,'ExaDG']]],
  ['lowstoragerk4stage5reg2c_154',['LowStorageRK4Stage5Reg2C',['../classExaDG_1_1LowStorageRK4Stage5Reg2C.html',1,'ExaDG']]],
  ['lowstoragerk4stage5reg3c_155',['LowStorageRK4Stage5Reg3C',['../classExaDG_1_1LowStorageRK4Stage5Reg3C.html',1,'ExaDG']]],
  ['lowstoragerk5stage9reg2s_156',['LowStorageRK5Stage9Reg2S',['../classExaDG_1_1LowStorageRK5Stage9Reg2S.html',1,'ExaDG']]],
  ['lowstoragerktd_157',['LowStorageRKTD',['../classExaDG_1_1LowStorageRKTD.html',1,'ExaDG']]]
];
