var searchData=
[
  ['serialize_272',['serialize',['../classdealspectrum_1_1Interpolator.html#a8283a193758ed7bc6fd68fd2f3cd9847',1,'dealspectrum::Interpolator::serialize(char const *filename)'],['../classdealspectrum_1_1Interpolator.html#a6b09f98b6b45095290fa3ea8269f0c16',1,'dealspectrum::Interpolator::serialize(char const *filename, double const *&amp;src)'],['../classdealspectrum_1_1SpectralAnalysis.html#a5823986be9b1e140e8a408cdcdd5b59c',1,'dealspectrum::SpectralAnalysis::serialize()']]],
  ['setup_273',['Setup',['../classdealspectrum_1_1Setup.html',1,'dealspectrum::Setup'],['../classdealspectrum_1_1Setup.html#ae48fcc6968bba36f4300ec7e88009717',1,'dealspectrum::Setup::Setup()']]],
  ['smootherbase_274',['SmootherBase',['../classExaDG_1_1SmootherBase.html',1,'ExaDG']]],
  ['smootherdata_275',['SmootherData',['../structExaDG_1_1SmootherData.html',1,'ExaDG']]],
  ['solutionfield_276',['SolutionField',['../classExaDG_1_1SolutionField.html',1,'ExaDG']]],
  ['solver_277',['Solver',['../classExaDG_1_1Newton_1_1Solver.html',1,'ExaDG::Newton']]],
  ['solverbase_278',['SolverBase',['../classExaDG_1_1Elementwise_1_1SolverBase.html',1,'ExaDG::Elementwise']]],
  ['solvercg_279',['SolverCG',['../classExaDG_1_1Elementwise_1_1SolverCG.html',1,'ExaDG::Elementwise']]],
  ['solverdata_280',['SolverData',['../structExaDG_1_1Newton_1_1SolverData.html',1,'ExaDG::Newton::SolverData'],['../structExaDG_1_1SolverData.html',1,'ExaDG::SolverData']]],
  ['solvergmres_281',['SolverGMRES',['../classExaDG_1_1Elementwise_1_1SolverGMRES.html',1,'ExaDG::Elementwise']]],
  ['solverinfodata_282',['SolverInfoData',['../structExaDG_1_1SolverInfoData.html',1,'ExaDG']]],
  ['solverresult_283',['SolverResult',['../structExaDG_1_1SolverResult.html',1,'ExaDG']]],
  ['spatialoperatorbase_284',['SpatialOperatorBase',['../classExaDG_1_1IncNS_1_1SpatialOperatorBase.html',1,'ExaDG::IncNS']]],
  ['spatialoperatorbase_3c_20dim_2c_20double_20_3e_285',['SpatialOperatorBase&lt; dim, double &gt;',['../classExaDG_1_1IncNS_1_1SpatialOperatorBase.html',1,'ExaDG::IncNS']]],
  ['spatialresolutionparameters_286',['SpatialResolutionParameters',['../structExaDG_1_1SpatialResolutionParameters.html',1,'ExaDG']]],
  ['spectralanalysis_287',['SpectralAnalysis',['../classdealspectrum_1_1SpectralAnalysis.html',1,'dealspectrum::SpectralAnalysis'],['../classdealspectrum_1_1SpectralAnalysis.html#a34a974fb314f0807d96902741be6e156',1,'dealspectrum::SpectralAnalysis::SpectralAnalysis()']]],
  ['ssprk_288',['SSPRK',['../classExaDG_1_1SSPRK.html',1,'ExaDG']]],
  ['start_289',['start',['../classdealspectrum_1_1DealSpectrumTimer.html#a140b943f9881e4a1d917941f896cb472',1,'dealspectrum::DealSpectrumTimer']]],
  ['statisticsdata_290',['StatisticsData',['../structExaDG_1_1IncNS_1_1StatisticsData.html',1,'ExaDG::IncNS']]],
  ['statisticsmanager_291',['StatisticsManager',['../classExaDG_1_1StatisticsManager.html',1,'ExaDG']]],
  ['stop_292',['stop',['../classdealspectrum_1_1DealSpectrumTimer.html#ac7f6fa0118b49c8c58f1b8357cc2a371',1,'dealspectrum::DealSpectrumTimer']]],
  ['streamfunctioncalculatorrhsoperator_293',['StreamfunctionCalculatorRHSOperator',['../classExaDG_1_1IncNS_1_1StreamfunctionCalculatorRHSOperator.html',1,'ExaDG::IncNS']]],
  ['stvenantkirchhoff_294',['StVenantKirchhoff',['../classExaDG_1_1Structure_1_1StVenantKirchhoff.html',1,'ExaDG::Structure']]],
  ['stvenantkirchhoffdata_295',['StVenantKirchhoffData',['../structExaDG_1_1Structure_1_1StVenantKirchhoffData.html',1,'ExaDG::Structure']]]
];
