var searchData=
[
  ['calculate_5fenergy_5fspectrum_0',['calculate_energy_spectrum',['../classdealspectrum_1_1SpectralAnalysis.html#a192f1677ecc3281dfe9f19628d06b14f',1,'dealspectrum::SpectralAnalysis']]],
  ['calculate_5ffilter_5fwidth_1',['calculate_filter_width',['../classExaDG_1_1IncNS_1_1TurbulenceModel.html#ae739ac5631983a50b2a5bf6e664c50b5',1,'ExaDG::IncNS::TurbulenceModel']]],
  ['calculate_5fgradient_5fflux_2',['calculate_gradient_flux',['../classExaDG_1_1IncNS_1_1Operators_1_1ViscousKernel.html#a231e82673d1fd134748a4605aed289dd',1,'ExaDG::IncNS::Operators::ViscousKernel']]],
  ['calculate_5fvalue_5fflux_3',['calculate_value_flux',['../classExaDG_1_1IncNS_1_1Operators_1_1ViscousKernel.html#a068b47893755fa37fe567bf3c01c021a',1,'ExaDG::IncNS::Operators::ViscousKernel']]],
  ['cgsmoother_4',['CGSmoother',['../classExaDG_1_1CGSmoother.html',1,'ExaDG']]],
  ['chebyshevsmoother_5',['ChebyshevSmoother',['../classExaDG_1_1ChebyshevSmoother.html',1,'ExaDG']]],
  ['checkmultigrid_6',['CheckMultigrid',['../classExaDG_1_1CheckMultigrid.html',1,'ExaDG']]],
  ['clear_7',['clear',['../classExaDG_1_1TimerTree.html#a2886f1d3bbd4e82cb54458d94fe82979',1,'ExaDG::TimerTree']]],
  ['coarse_5fperiodic_5fface_5fpairs_8',['coarse_periodic_face_pairs',['../classExaDG_1_1Grid.html#aa9e786659b6d2b2657a75710efc3295e',1,'ExaDG::Grid']]],
  ['coarse_5ftriangulations_9',['coarse_triangulations',['../classExaDG_1_1Grid.html#adb00c7653c234f42a17eb41b48587acf',1,'ExaDG::Grid']]],
  ['coarsegriddata_10',['CoarseGridData',['../structExaDG_1_1CoarseGridData.html',1,'ExaDG']]],
  ['combinedoperator_11',['CombinedOperator',['../classExaDG_1_1CompNS_1_1CombinedOperator.html',1,'ExaDG::CompNS::CombinedOperator&lt; dim, Number &gt;'],['../classExaDG_1_1ConvDiff_1_1CombinedOperator.html',1,'ExaDG::ConvDiff::CombinedOperator&lt; dim, Number &gt;']]],
  ['combinedoperatordata_12',['CombinedOperatorData',['../structExaDG_1_1CompNS_1_1CombinedOperatorData.html',1,'ExaDG::CompNS::CombinedOperatorData&lt; dim &gt;'],['../structExaDG_1_1ConvDiff_1_1CombinedOperatorData.html',1,'ExaDG::ConvDiff::CombinedOperatorData&lt; dim &gt;']]],
  ['configurationparameters_13',['ConfigurationParameters',['../structExaDG_1_1preCICE_1_1ConfigurationParameters.html',1,'ExaDG::preCICE']]],
  ['containerinterfacedata_14',['ContainerInterfaceData',['../classExaDG_1_1ContainerInterfaceData.html',1,'ExaDG']]],
  ['continuitypenaltydata_15',['ContinuityPenaltyData',['../structExaDG_1_1IncNS_1_1ContinuityPenaltyData.html',1,'ExaDG::IncNS']]],
  ['continuitypenaltykernel_16',['ContinuityPenaltyKernel',['../classExaDG_1_1IncNS_1_1Operators_1_1ContinuityPenaltyKernel.html',1,'ExaDG::IncNS::Operators']]],
  ['continuitypenaltykerneldata_17',['ContinuityPenaltyKernelData',['../structExaDG_1_1IncNS_1_1Operators_1_1ContinuityPenaltyKernelData.html',1,'ExaDG::IncNS::Operators']]],
  ['continuitypenaltyoperator_18',['ContinuityPenaltyOperator',['../classExaDG_1_1IncNS_1_1ContinuityPenaltyOperator.html',1,'ExaDG::IncNS']]],
  ['continuitypenaltyoperator_3c_20dim_2c_20double_20_3e_19',['ContinuityPenaltyOperator&lt; dim, double &gt;',['../classExaDG_1_1IncNS_1_1ContinuityPenaltyOperator.html',1,'ExaDG::IncNS']]],
  ['convectivekernel_20',['ConvectiveKernel',['../classExaDG_1_1ConvDiff_1_1Operators_1_1ConvectiveKernel.html',1,'ExaDG::ConvDiff::Operators::ConvectiveKernel&lt; dim, Number &gt;'],['../classExaDG_1_1IncNS_1_1Operators_1_1ConvectiveKernel.html',1,'ExaDG::IncNS::Operators::ConvectiveKernel&lt; dim, Number &gt;']]],
  ['convectivekerneldata_21',['ConvectiveKernelData',['../structExaDG_1_1ConvDiff_1_1Operators_1_1ConvectiveKernelData.html',1,'ExaDG::ConvDiff::Operators::ConvectiveKernelData&lt; dim &gt;'],['../structExaDG_1_1IncNS_1_1Operators_1_1ConvectiveKernelData.html',1,'ExaDG::IncNS::Operators::ConvectiveKernelData']]],
  ['convectiveoperator_22',['ConvectiveOperator',['../classExaDG_1_1CompNS_1_1ConvectiveOperator.html',1,'ExaDG::CompNS::ConvectiveOperator&lt; dim, Number &gt;'],['../classExaDG_1_1ConvDiff_1_1ConvectiveOperator.html',1,'ExaDG::ConvDiff::ConvectiveOperator&lt; dim, Number &gt;'],['../classExaDG_1_1IncNS_1_1ConvectiveOperator.html',1,'ExaDG::IncNS::ConvectiveOperator&lt; dim, Number &gt;']]],
  ['convectiveoperator_3c_20dim_2c_20double_20_3e_23',['ConvectiveOperator&lt; dim, double &gt;',['../classExaDG_1_1IncNS_1_1ConvectiveOperator.html',1,'ExaDG::IncNS']]],
  ['convectiveoperatordata_24',['ConvectiveOperatorData',['../structExaDG_1_1CompNS_1_1ConvectiveOperatorData.html',1,'ExaDG::CompNS::ConvectiveOperatorData&lt; dim &gt;'],['../structExaDG_1_1ConvDiff_1_1ConvectiveOperatorData.html',1,'ExaDG::ConvDiff::ConvectiveOperatorData&lt; dim &gt;'],['../structExaDG_1_1IncNS_1_1ConvectiveOperatorData.html',1,'ExaDG::IncNS::ConvectiveOperatorData&lt; dim &gt;']]],
  ['copy_5fto_5fmg_25',['copy_to_mg',['../classExaDG_1_1MGTransferH.html#a9c0e0187ca29cbeff492774a99979ddf',1,'ExaDG::MGTransferH']]],
  ['couplingbase_26',['CouplingBase',['../classExaDG_1_1preCICE_1_1CouplingBase.html',1,'ExaDG::preCICE']]],
  ['create_5fdirectories_27',['create_directories',['../namespaceExaDG.html#ae37213007b3d71515b9d35a598e17e22',1,'ExaDG']]],
  ['create_5fsubdivided_5fhyper_5frectangle_28',['create_subdivided_hyper_rectangle',['../namespaceExaDG.html#a11fdfa75b66139f3547f5ed4d7c1ef58',1,'ExaDG']]],
  ['cubemeshmovementfunctions_29',['CubeMeshMovementFunctions',['../classExaDG_1_1CubeMeshMovementFunctions.html',1,'ExaDG']]],
  ['curlcompute_30',['CurlCompute',['../structExaDG_1_1IncNS_1_1CurlCompute.html',1,'ExaDG::IncNS']]],
  ['curlcompute_3c_202_2c_20feeval_20_3e_31',['CurlCompute&lt; 2, FEEval &gt;',['../structExaDG_1_1IncNS_1_1CurlCompute_3_012_00_01FEEval_01_4.html',1,'ExaDG::IncNS']]]
];
