var searchData=
[
  ['serialize_272',['serialize',['../classdealspectrum_1_1Interpolator.html#a8283a193758ed7bc6fd68fd2f3cd9847',1,'dealspectrum::Interpolator::serialize(char const *filename)'],['../classdealspectrum_1_1Interpolator.html#a6b09f98b6b45095290fa3ea8269f0c16',1,'dealspectrum::Interpolator::serialize(char const *filename, double const *&amp;src)'],['../classdealspectrum_1_1SpectralAnalysis.html#a5823986be9b1e140e8a408cdcdd5b59c',1,'dealspectrum::SpectralAnalysis::serialize()']]],
  ['setup_273',['Setup',['../classdealspectrum_1_1Setup.html',1,'dealspectrum::Setup'],['../classdealspectrum_1_1Setup.html#ae48fcc6968bba36f4300ec7e88009717',1,'dealspectrum::Setup::Setup()']]],
  ['smootherbase_274',['SmootherBase',['../classExaDG_1_1SmootherBase.html',1,'ExaDG']]],
  ['smootherdata_275',['SmootherData',['../structExaDG_1_1SmootherData.html',1,'ExaDG']]],
  ['solutionfield_276',['SolutionField',['../classExaDG_1_1SolutionField.html',1,'ExaDG']]],
  ['solver_277',['Solver',['../classExaDG_1_1Newton_1_1Solver.html',1,'ExaDG::Newton']]],
  ['solverbase_278',['SolverBase',['../classExaDG_1_1Elementwise_1_1SolverBase.html',1,'ExaDG::Elementwise::SolverBase&lt; value_type, Matrix, Preconditioner &gt;'],['../classExaDG_1_1Krylov_1_1SolverBase.html',1,'ExaDG::Krylov::SolverBase&lt; VectorType &gt;']]],
  ['solverbase_3c_20linearalgebra_3a_3adistributed_3a_3avector_3c_20number_20_3e_20_3e_279',['SolverBase&lt; LinearAlgebra::distributed::Vector&lt; Number &gt; &gt;',['../classExaDG_1_1Krylov_1_1SolverBase.html',1,'ExaDG::Krylov']]],
  ['solvercg_280',['SolverCG',['../classExaDG_1_1Elementwise_1_1SolverCG.html',1,'ExaDG::Elementwise::SolverCG&lt; value_type, Matrix, Preconditioner &gt;'],['../classExaDG_1_1Krylov_1_1SolverCG.html',1,'ExaDG::Krylov::SolverCG&lt; Operator, Preconditioner, VectorType &gt;']]],
  ['solverdata_281',['SolverData',['../structExaDG_1_1Newton_1_1SolverData.html',1,'ExaDG::Newton::SolverData'],['../structExaDG_1_1SolverData.html',1,'ExaDG::SolverData']]],
  ['solverdatacg_282',['SolverDataCG',['../structExaDG_1_1Krylov_1_1SolverDataCG.html',1,'ExaDG::Krylov']]],
  ['solverdatafgmres_283',['SolverDataFGMRES',['../structExaDG_1_1Krylov_1_1SolverDataFGMRES.html',1,'ExaDG::Krylov']]],
  ['solverdatagmres_284',['SolverDataGMRES',['../structExaDG_1_1Krylov_1_1SolverDataGMRES.html',1,'ExaDG::Krylov']]],
  ['solverfgmres_285',['SolverFGMRES',['../classExaDG_1_1Krylov_1_1SolverFGMRES.html',1,'ExaDG::Krylov']]],
  ['solvergmres_286',['SolverGMRES',['../classExaDG_1_1Elementwise_1_1SolverGMRES.html',1,'ExaDG::Elementwise::SolverGMRES&lt; value_type, Matrix, Preconditioner &gt;'],['../classExaDG_1_1Krylov_1_1SolverGMRES.html',1,'ExaDG::Krylov::SolverGMRES&lt; Operator, Preconditioner, VectorType &gt;']]],
  ['solverinfodata_287',['SolverInfoData',['../structExaDG_1_1SolverInfoData.html',1,'ExaDG']]],
  ['solverresult_288',['SolverResult',['../structExaDG_1_1SolverResult.html',1,'ExaDG']]],
  ['spatialoperatorbase_289',['SpatialOperatorBase',['../classExaDG_1_1IncNS_1_1SpatialOperatorBase.html',1,'ExaDG::IncNS']]],
  ['spatialoperatorbase_3c_20dim_2c_20double_20_3e_290',['SpatialOperatorBase&lt; dim, double &gt;',['../classExaDG_1_1IncNS_1_1SpatialOperatorBase.html',1,'ExaDG::IncNS']]],
  ['spatialresolutionparameters_291',['SpatialResolutionParameters',['../structExaDG_1_1SpatialResolutionParameters.html',1,'ExaDG']]],
  ['spectralanalysis_292',['SpectralAnalysis',['../classdealspectrum_1_1SpectralAnalysis.html',1,'dealspectrum::SpectralAnalysis'],['../classdealspectrum_1_1SpectralAnalysis.html#a34a974fb314f0807d96902741be6e156',1,'dealspectrum::SpectralAnalysis::SpectralAnalysis()']]],
  ['ssprk_293',['SSPRK',['../classExaDG_1_1SSPRK.html',1,'ExaDG']]],
  ['start_294',['start',['../classdealspectrum_1_1DealSpectrumTimer.html#a140b943f9881e4a1d917941f896cb472',1,'dealspectrum::DealSpectrumTimer']]],
  ['statisticsdata_295',['StatisticsData',['../structExaDG_1_1IncNS_1_1StatisticsData.html',1,'ExaDG::IncNS']]],
  ['statisticsmanager_296',['StatisticsManager',['../classExaDG_1_1StatisticsManager.html',1,'ExaDG']]],
  ['stop_297',['stop',['../classdealspectrum_1_1DealSpectrumTimer.html#ac7f6fa0118b49c8c58f1b8357cc2a371',1,'dealspectrum::DealSpectrumTimer']]],
  ['streamfunctioncalculatorrhsoperator_298',['StreamfunctionCalculatorRHSOperator',['../classExaDG_1_1IncNS_1_1StreamfunctionCalculatorRHSOperator.html',1,'ExaDG::IncNS']]],
  ['stvenantkirchhoff_299',['StVenantKirchhoff',['../classExaDG_1_1Structure_1_1StVenantKirchhoff.html',1,'ExaDG::Structure']]],
  ['stvenantkirchhoffdata_300',['StVenantKirchhoffData',['../structExaDG_1_1Structure_1_1StVenantKirchhoffData.html',1,'ExaDG::Structure']]]
];
