var searchData=
[
  ['serialize_0',['serialize',['../classdealspectrum_1_1Interpolator.html#a8283a193758ed7bc6fd68fd2f3cd9847',1,'dealspectrum::Interpolator::serialize(char const *filename)'],['../classdealspectrum_1_1Interpolator.html#a6b09f98b6b45095290fa3ea8269f0c16',1,'dealspectrum::Interpolator::serialize(char const *filename, double const *&amp;src)'],['../classdealspectrum_1_1SpectralAnalysis.html#a5823986be9b1e140e8a408cdcdd5b59c',1,'dealspectrum::SpectralAnalysis::serialize()']]],
  ['setup_1',['Setup',['../classdealspectrum_1_1Setup.html',1,'dealspectrum::Setup'],['../classdealspectrum_1_1Setup.html#ae48fcc6968bba36f4300ec7e88009717',1,'dealspectrum::Setup::Setup()']]],
  ['setup_2',['setup',['../classExaDG_1_1InterfaceCoupling.html#a56a1527c3c5de8e9c3c96b3761c35a45',1,'ExaDG::InterfaceCoupling']]],
  ['smootherbase_3',['SmootherBase',['../classExaDG_1_1SmootherBase.html',1,'ExaDG']]],
  ['smootherdata_4',['SmootherData',['../structExaDG_1_1SmootherData.html',1,'ExaDG']]],
  ['solutionfield_5',['SolutionField',['../classExaDG_1_1SolutionField.html',1,'ExaDG']]],
  ['solver_6',['Solver',['../classExaDG_1_1Newton_1_1Solver.html',1,'ExaDG::Newton']]],
  ['solverbase_7',['SolverBase',['../classExaDG_1_1Elementwise_1_1SolverBase.html',1,'ExaDG::Elementwise::SolverBase&lt; value_type, Matrix, Preconditioner &gt;'],['../classExaDG_1_1Krylov_1_1SolverBase.html',1,'ExaDG::Krylov::SolverBase&lt; VectorType &gt;']]],
  ['solverbase_3c_20dealii_3a_3alinearalgebra_3a_3adistributed_3a_3avector_3c_20number_20_3e_20_3e_8',['SolverBase&lt; dealii::LinearAlgebra::distributed::Vector&lt; Number &gt; &gt;',['../classExaDG_1_1Krylov_1_1SolverBase.html',1,'ExaDG::Krylov']]],
  ['solvercg_9',['SolverCG',['../classExaDG_1_1Elementwise_1_1SolverCG.html',1,'ExaDG::Elementwise::SolverCG&lt; value_type, Matrix, Preconditioner &gt;'],['../classExaDG_1_1Krylov_1_1SolverCG.html',1,'ExaDG::Krylov::SolverCG&lt; Operator, Preconditioner, VectorType &gt;']]],
  ['solverdata_10',['SolverData',['../structExaDG_1_1Newton_1_1SolverData.html',1,'ExaDG::Newton::SolverData'],['../structExaDG_1_1SolverData.html',1,'ExaDG::SolverData']]],
  ['solverdatacg_11',['SolverDataCG',['../structExaDG_1_1Krylov_1_1SolverDataCG.html',1,'ExaDG::Krylov']]],
  ['solverdatafgmres_12',['SolverDataFGMRES',['../structExaDG_1_1Krylov_1_1SolverDataFGMRES.html',1,'ExaDG::Krylov']]],
  ['solverdatagmres_13',['SolverDataGMRES',['../structExaDG_1_1Krylov_1_1SolverDataGMRES.html',1,'ExaDG::Krylov']]],
  ['solverfgmres_14',['SolverFGMRES',['../classExaDG_1_1Krylov_1_1SolverFGMRES.html',1,'ExaDG::Krylov']]],
  ['solverfluid_15',['SolverFluid',['../classExaDG_1_1FSI_1_1SolverFluid.html',1,'ExaDG::FSI']]],
  ['solvergmres_16',['SolverGMRES',['../classExaDG_1_1Elementwise_1_1SolverGMRES.html',1,'ExaDG::Elementwise::SolverGMRES&lt; value_type, Matrix, Preconditioner &gt;'],['../classExaDG_1_1Krylov_1_1SolverGMRES.html',1,'ExaDG::Krylov::SolverGMRES&lt; Operator, Preconditioner, VectorType &gt;']]],
  ['solverinfodata_17',['SolverInfoData',['../structExaDG_1_1SolverInfoData.html',1,'ExaDG']]],
  ['solverpoisson_18',['SolverPoisson',['../classExaDG_1_1Poisson_1_1SolverPoisson.html',1,'ExaDG::Poisson']]],
  ['solverresult_19',['SolverResult',['../structExaDG_1_1SolverResult.html',1,'ExaDG']]],
  ['solverstructure_20',['SolverStructure',['../classExaDG_1_1FSI_1_1SolverStructure.html',1,'ExaDG::FSI']]],
  ['spatialoperatorbase_21',['SpatialOperatorBase',['../classExaDG_1_1IncNS_1_1SpatialOperatorBase.html',1,'ExaDG::IncNS']]],
  ['spatialoperatorbase_3c_20dim_2c_20double_20_3e_22',['SpatialOperatorBase&lt; dim, double &gt;',['../classExaDG_1_1IncNS_1_1SpatialOperatorBase.html',1,'ExaDG::IncNS']]],
  ['spatialresolutionparameters_23',['SpatialResolutionParameters',['../structExaDG_1_1SpatialResolutionParameters.html',1,'ExaDG']]],
  ['spectralanalysis_24',['SpectralAnalysis',['../classdealspectrum_1_1SpectralAnalysis.html',1,'dealspectrum::SpectralAnalysis'],['../classdealspectrum_1_1SpectralAnalysis.html#a34a974fb314f0807d96902741be6e156',1,'dealspectrum::SpectralAnalysis::SpectralAnalysis()']]],
  ['ssprk_25',['SSPRK',['../classExaDG_1_1SSPRK.html',1,'ExaDG']]],
  ['start_26',['start',['../classdealspectrum_1_1DealSpectrumTimer.html#a140b943f9881e4a1d917941f896cb472',1,'dealspectrum::DealSpectrumTimer']]],
  ['statisticsdata_27',['StatisticsData',['../structExaDG_1_1IncNS_1_1StatisticsData.html',1,'ExaDG::IncNS']]],
  ['statisticsmanager_28',['StatisticsManager',['../classExaDG_1_1StatisticsManager.html',1,'ExaDG']]],
  ['stop_29',['stop',['../classdealspectrum_1_1DealSpectrumTimer.html#ac7f6fa0118b49c8c58f1b8357cc2a371',1,'dealspectrum::DealSpectrumTimer']]],
  ['streamfunctioncalculatorrhsoperator_30',['StreamfunctionCalculatorRHSOperator',['../classExaDG_1_1IncNS_1_1StreamfunctionCalculatorRHSOperator.html',1,'ExaDG::IncNS']]],
  ['stvenantkirchhoff_31',['StVenantKirchhoff',['../classExaDG_1_1Structure_1_1StVenantKirchhoff.html',1,'ExaDG::Structure']]],
  ['stvenantkirchhoffdata_32',['StVenantKirchhoffData',['../structExaDG_1_1Structure_1_1StVenantKirchhoffData.html',1,'ExaDG::Structure']]]
];
