var searchData=
[
  ['valid_5fdeformation_0',['valid_deformation',['../classExaDG_1_1Structure_1_1NonLinearOperator.html#a5b6c5ca383e783c22da2f2eb03fb8266',1,'ExaDG::Structure::NonLinearOperator']]],
  ['variablecoefficients_1',['VariableCoefficients',['../classExaDG_1_1VariableCoefficients.html',1,'ExaDG']]],
  ['variablecoefficients_3c_20dealii_3a_3avectorizedarray_3c_20double_20_3e_20_3e_2',['VariableCoefficients&lt; dealii::VectorizedArray&lt; double &gt; &gt;',['../classExaDG_1_1VariableCoefficients.html',1,'ExaDG']]],
  ['variablecoefficients_3c_20dealii_3a_3avectorizedarray_3c_20number_20_3e_20_3e_3',['VariableCoefficients&lt; dealii::VectorizedArray&lt; Number &gt; &gt;',['../classExaDG_1_1VariableCoefficients.html',1,'ExaDG']]],
  ['varies_5fin_5fspace_4',['varies_in_space',['../classExaDG_1_1Utilities_1_1SpatialAwareFunction.html#a16d29f3b654cc8dc40947885851b0800',1,'ExaDG::Utilities::SpatialAwareFunction']]],
  ['vectortype_5',['VectorType',['../classExaDG_1_1CompNS_1_1PostProcessorInterface.html',1,'ExaDG::CompNS::VectorType&lt; Number &gt;'],['../classExaDG_1_1ConvDiff_1_1PostProcessorInterface.html',1,'ExaDG::ConvDiff::VectorType&lt; Number &gt;'],['../classExaDG_1_1IncNS_1_1PostProcessorInterface.html',1,'ExaDG::IncNS::VectorType&lt; Number &gt;'],['../classExaDG_1_1Poisson_1_1PostProcessorInterface.html',1,'ExaDG::Poisson::VectorType&lt; Number &gt;'],['../classExaDG_1_1PreconditionerBase.html',1,'ExaDG::VectorType&lt; Number &gt;'],['../classExaDG_1_1PreconditionerBase.html',1,'ExaDG::VectorType&lt; value_type &gt;'],['../classExaDG_1_1Structure_1_1PostProcessorBase.html',1,'ExaDG::Structure::VectorType&lt; Number &gt;']]],
  ['vectorwriter_6',['VectorWriter',['../classExaDG_1_1VectorWriter.html',1,'ExaDG']]],
  ['velocityprojection_7',['VelocityProjection',['../classExaDG_1_1VelocityProjection.html',1,'ExaDG']]],
  ['viscositycalculator_8',['ViscosityCalculator',['../classExaDG_1_1ViscosityCalculator.html',1,'ExaDG']]],
  ['viscositycalculator_3c_20dim_2c_20double_20_3e_9',['ViscosityCalculator&lt; dim, double &gt;',['../classExaDG_1_1ViscosityCalculator.html',1,'ExaDG']]],
  ['viscositymodelbase_10',['ViscosityModelBase',['../classExaDG_1_1IncNS_1_1ViscosityModelBase.html',1,'ExaDG::IncNS']]],
  ['viscositymodelbase_3c_20dim_2c_20double_20_3e_11',['ViscosityModelBase&lt; dim, double &gt;',['../classExaDG_1_1IncNS_1_1ViscosityModelBase.html',1,'ExaDG::IncNS']]],
  ['viscouskernel_12',['ViscousKernel',['../classExaDG_1_1IncNS_1_1Operators_1_1ViscousKernel.html',1,'ExaDG::IncNS::Operators']]],
  ['viscouskernel_3c_20dim_2c_20double_20_3e_13',['ViscousKernel&lt; dim, double &gt;',['../classExaDG_1_1IncNS_1_1Operators_1_1ViscousKernel.html',1,'ExaDG::IncNS::Operators']]],
  ['viscouskerneldata_14',['ViscousKernelData',['../structExaDG_1_1IncNS_1_1Operators_1_1ViscousKernelData.html',1,'ExaDG::IncNS::Operators']]],
  ['viscousoperator_15',['ViscousOperator',['../classExaDG_1_1CompNS_1_1ViscousOperator.html',1,'ExaDG::CompNS::ViscousOperator&lt; dim, Number &gt;'],['../classExaDG_1_1IncNS_1_1ViscousOperator.html',1,'ExaDG::IncNS::ViscousOperator&lt; dim, Number &gt;']]],
  ['viscousoperator_3c_20dim_2c_20double_20_3e_16',['ViscousOperator&lt; dim, double &gt;',['../classExaDG_1_1IncNS_1_1ViscousOperator.html',1,'ExaDG::IncNS']]],
  ['viscousoperatordata_17',['ViscousOperatorData',['../structExaDG_1_1CompNS_1_1ViscousOperatorData.html',1,'ExaDG::CompNS::ViscousOperatorData&lt; dim &gt;'],['../structExaDG_1_1IncNS_1_1ViscousOperatorData.html',1,'ExaDG::IncNS::ViscousOperatorData&lt; dim &gt;']]],
  ['vmult_18',['vmult',['../classExaDG_1_1Elementwise_1_1JacobiPreconditioner.html#a3388ed26e11f59571d3e8ab6e45d7bce',1,'ExaDG::Elementwise::JacobiPreconditioner::vmult()'],['../classExaDG_1_1Elementwise_1_1InverseMassPreconditioner.html#a1f480ae1482708fd0fe5d377fe24e102',1,'ExaDG::Elementwise::InverseMassPreconditioner::vmult()']]],
  ['volumecoupling_19',['VolumeCoupling',['../classExaDG_1_1AeroAcoustic_1_1VolumeCoupling.html',1,'ExaDG::AeroAcoustic']]],
  ['vorticitycalculator_20',['VorticityCalculator',['../classExaDG_1_1VorticityCalculator.html',1,'ExaDG']]],
  ['vorticitycalculator_3c_20dim_2c_20double_20_3e_21',['VorticityCalculator&lt; dim, double &gt;',['../classExaDG_1_1VorticityCalculator.html',1,'ExaDG']]]
];
