var searchData=
[
  ['setup_571',['Setup',['../classdealspectrum_1_1Setup.html',1,'dealspectrum']]],
  ['smootherbase_572',['SmootherBase',['../classExaDG_1_1SmootherBase.html',1,'ExaDG']]],
  ['smootherdata_573',['SmootherData',['../structExaDG_1_1SmootherData.html',1,'ExaDG']]],
  ['solutionfield_574',['SolutionField',['../classExaDG_1_1SolutionField.html',1,'ExaDG']]],
  ['solver_575',['Solver',['../classExaDG_1_1Newton_1_1Solver.html',1,'ExaDG::Newton']]],
  ['solverbase_576',['SolverBase',['../classExaDG_1_1Elementwise_1_1SolverBase.html',1,'ExaDG::Elementwise::SolverBase&lt; value_type, Matrix, Preconditioner &gt;'],['../classExaDG_1_1Krylov_1_1SolverBase.html',1,'ExaDG::Krylov::SolverBase&lt; VectorType &gt;']]],
  ['solverbase_3c_20linearalgebra_3a_3adistributed_3a_3avector_3c_20number_20_3e_20_3e_577',['SolverBase&lt; LinearAlgebra::distributed::Vector&lt; Number &gt; &gt;',['../classExaDG_1_1Krylov_1_1SolverBase.html',1,'ExaDG::Krylov']]],
  ['solvercg_578',['SolverCG',['../classExaDG_1_1Elementwise_1_1SolverCG.html',1,'ExaDG::Elementwise::SolverCG&lt; value_type, Matrix, Preconditioner &gt;'],['../classExaDG_1_1Krylov_1_1SolverCG.html',1,'ExaDG::Krylov::SolverCG&lt; Operator, Preconditioner, VectorType &gt;']]],
  ['solverdata_579',['SolverData',['../structExaDG_1_1Newton_1_1SolverData.html',1,'ExaDG::Newton::SolverData'],['../structExaDG_1_1SolverData.html',1,'ExaDG::SolverData']]],
  ['solverdatacg_580',['SolverDataCG',['../structExaDG_1_1Krylov_1_1SolverDataCG.html',1,'ExaDG::Krylov']]],
  ['solverdatafgmres_581',['SolverDataFGMRES',['../structExaDG_1_1Krylov_1_1SolverDataFGMRES.html',1,'ExaDG::Krylov']]],
  ['solverdatagmres_582',['SolverDataGMRES',['../structExaDG_1_1Krylov_1_1SolverDataGMRES.html',1,'ExaDG::Krylov']]],
  ['solverfgmres_583',['SolverFGMRES',['../classExaDG_1_1Krylov_1_1SolverFGMRES.html',1,'ExaDG::Krylov']]],
  ['solvergmres_584',['SolverGMRES',['../classExaDG_1_1Elementwise_1_1SolverGMRES.html',1,'ExaDG::Elementwise::SolverGMRES&lt; value_type, Matrix, Preconditioner &gt;'],['../classExaDG_1_1Krylov_1_1SolverGMRES.html',1,'ExaDG::Krylov::SolverGMRES&lt; Operator, Preconditioner, VectorType &gt;']]],
  ['solverinfodata_585',['SolverInfoData',['../structExaDG_1_1SolverInfoData.html',1,'ExaDG']]],
  ['solverresult_586',['SolverResult',['../structExaDG_1_1SolverResult.html',1,'ExaDG']]],
  ['spatialoperatorbase_587',['SpatialOperatorBase',['../classExaDG_1_1IncNS_1_1SpatialOperatorBase.html',1,'ExaDG::IncNS']]],
  ['spatialoperatorbase_3c_20dim_2c_20double_20_3e_588',['SpatialOperatorBase&lt; dim, double &gt;',['../classExaDG_1_1IncNS_1_1SpatialOperatorBase.html',1,'ExaDG::IncNS']]],
  ['spatialresolutionparameters_589',['SpatialResolutionParameters',['../structExaDG_1_1SpatialResolutionParameters.html',1,'ExaDG']]],
  ['spectralanalysis_590',['SpectralAnalysis',['../classdealspectrum_1_1SpectralAnalysis.html',1,'dealspectrum']]],
  ['ssprk_591',['SSPRK',['../classExaDG_1_1SSPRK.html',1,'ExaDG']]],
  ['statisticsdata_592',['StatisticsData',['../structExaDG_1_1IncNS_1_1StatisticsData.html',1,'ExaDG::IncNS']]],
  ['statisticsmanager_593',['StatisticsManager',['../classExaDG_1_1StatisticsManager.html',1,'ExaDG']]],
  ['streamfunctioncalculatorrhsoperator_594',['StreamfunctionCalculatorRHSOperator',['../classExaDG_1_1IncNS_1_1StreamfunctionCalculatorRHSOperator.html',1,'ExaDG::IncNS']]],
  ['stvenantkirchhoff_595',['StVenantKirchhoff',['../classExaDG_1_1Structure_1_1StVenantKirchhoff.html',1,'ExaDG::Structure']]],
  ['stvenantkirchhoffdata_596',['StVenantKirchhoffData',['../structExaDG_1_1Structure_1_1StVenantKirchhoffData.html',1,'ExaDG::Structure']]]
];
