var searchData=
[
  ['laplacekernel_437',['LaplaceKernel',['../classExaDG_1_1Poisson_1_1Operators_1_1LaplaceKernel.html',1,'ExaDG::Poisson::Operators']]],
  ['laplacekernel_3c_20dim_2c_20number_2c_20n_5fcomponents_20_3e_438',['LaplaceKernel&lt; dim, Number, n_components &gt;',['../classExaDG_1_1Poisson_1_1Operators_1_1LaplaceKernel.html',1,'ExaDG::Poisson::Operators']]],
  ['laplacekerneldata_439',['LaplaceKernelData',['../structExaDG_1_1Poisson_1_1Operators_1_1LaplaceKernelData.html',1,'ExaDG::Poisson::Operators']]],
  ['laplaceoperator_440',['LaplaceOperator',['../classExaDG_1_1Poisson_1_1LaplaceOperator.html',1,'ExaDG::Poisson']]],
  ['laplaceoperator_3c_20dim_2c_20number_2c_201_20_3e_441',['LaplaceOperator&lt; dim, Number, 1 &gt;',['../classExaDG_1_1Poisson_1_1LaplaceOperator.html',1,'ExaDG::Poisson']]],
  ['laplaceoperatordata_442',['LaplaceOperatorData',['../structExaDG_1_1Poisson_1_1LaplaceOperatorData.html',1,'ExaDG::Poisson']]],
  ['lazy_5fptr_443',['lazy_ptr',['../classExaDG_1_1lazy__ptr.html',1,'ExaDG']]],
  ['lazy_5fptr_3c_20affineconstraints_3c_20number_20_3e_20_3e_444',['lazy_ptr&lt; AffineConstraints&lt; Number &gt; &gt;',['../classExaDG_1_1lazy__ptr.html',1,'ExaDG']]],
  ['lazy_5fptr_3c_20matrixfree_3c_20dim_2c_20number_20_3e_20_3e_445',['lazy_ptr&lt; MatrixFree&lt; dim, Number &gt; &gt;',['../classExaDG_1_1lazy__ptr.html',1,'ExaDG']]],
  ['lazy_5fptr_3c_20vectortype_20_3e_446',['lazy_ptr&lt; VectorType &gt;',['../classExaDG_1_1lazy__ptr.html',1,'ExaDG']]],
  ['liftanddragcalculator_447',['LiftAndDragCalculator',['../classExaDG_1_1LiftAndDragCalculator.html',1,'ExaDG']]],
  ['liftanddragdata_448',['LiftAndDragData',['../structExaDG_1_1LiftAndDragData.html',1,'ExaDG']]],
  ['line_449',['Line',['../structExaDG_1_1IncNS_1_1Line.html',1,'ExaDG::IncNS']]],
  ['linearizedoperator_450',['LinearizedOperator',['../classExaDG_1_1Structure_1_1LinearizedOperator.html',1,'ExaDG::Structure']]],
  ['linearoperator_451',['LinearOperator',['../classExaDG_1_1Structure_1_1LinearOperator.html',1,'ExaDG::Structure']]],
  ['linearoperatorcoupled_452',['LinearOperatorCoupled',['../classExaDG_1_1IncNS_1_1LinearOperatorCoupled.html',1,'ExaDG::IncNS']]],
  ['linearoperatorcoupled_3c_20dim_2c_20double_20_3e_453',['LinearOperatorCoupled&lt; dim, double &gt;',['../classExaDG_1_1IncNS_1_1LinearOperatorCoupled.html',1,'ExaDG::IncNS']]],
  ['linecircumferentialaveraging_454',['LineCircumferentialAveraging',['../structExaDG_1_1IncNS_1_1LineCircumferentialAveraging.html',1,'ExaDG::IncNS']]],
  ['linehomogeneousaveraging_455',['LineHomogeneousAveraging',['../structExaDG_1_1IncNS_1_1LineHomogeneousAveraging.html',1,'ExaDG::IncNS']]],
  ['lineplotcalculator_456',['LinePlotCalculator',['../classExaDG_1_1IncNS_1_1LinePlotCalculator.html',1,'ExaDG::IncNS']]],
  ['lineplotcalculatorstatistics_457',['LinePlotCalculatorStatistics',['../classExaDG_1_1IncNS_1_1LinePlotCalculatorStatistics.html',1,'ExaDG::IncNS']]],
  ['lineplotcalculatorstatisticshomogeneous_458',['LinePlotCalculatorStatisticsHomogeneous',['../classExaDG_1_1IncNS_1_1LinePlotCalculatorStatisticsHomogeneous.html',1,'ExaDG::IncNS']]],
  ['lineplotdata_459',['LinePlotData',['../structExaDG_1_1IncNS_1_1LinePlotData.html',1,'ExaDG::IncNS']]],
  ['lineplotdatainstantaneous_460',['LinePlotDataInstantaneous',['../structExaDG_1_1IncNS_1_1LinePlotDataInstantaneous.html',1,'ExaDG::IncNS']]],
  ['lineplotdatastatistics_461',['LinePlotDataStatistics',['../structExaDG_1_1IncNS_1_1LinePlotDataStatistics.html',1,'ExaDG::IncNS']]],
  ['lowstoragerk3stage4reg2c_462',['LowStorageRK3Stage4Reg2C',['../classExaDG_1_1LowStorageRK3Stage4Reg2C.html',1,'ExaDG']]],
  ['lowstoragerk4stage5reg2c_463',['LowStorageRK4Stage5Reg2C',['../classExaDG_1_1LowStorageRK4Stage5Reg2C.html',1,'ExaDG']]],
  ['lowstoragerk4stage5reg3c_464',['LowStorageRK4Stage5Reg3C',['../classExaDG_1_1LowStorageRK4Stage5Reg3C.html',1,'ExaDG']]],
  ['lowstoragerk5stage9reg2s_465',['LowStorageRK5Stage9Reg2S',['../classExaDG_1_1LowStorageRK5Stage9Reg2S.html',1,'ExaDG']]],
  ['lowstoragerktd_466',['LowStorageRKTD',['../classExaDG_1_1LowStorageRKTD.html',1,'ExaDG']]]
];
