var searchData=
[
  ['scalar_0',['scalar',['../classExaDG_1_1Structure_1_1Material.html',1,'ExaDG::Structure']]],
  ['scalarbase_1',['ScalarBase',['../classExaDG_1_1FTI_1_1ScalarBase.html',1,'ExaDG::FTI']]],
  ['setup_2',['Setup',['../classdealspectrum_1_1Setup.html',1,'dealspectrum']]],
  ['shearratecalculator_3',['ShearRateCalculator',['../classExaDG_1_1ShearRateCalculator.html',1,'ExaDG']]],
  ['shearratecalculator_3c_20dim_2c_20double_20_3e_4',['ShearRateCalculator&lt; dim, double &gt;',['../classExaDG_1_1ShearRateCalculator.html',1,'ExaDG']]],
  ['smootherbase_5',['SmootherBase',['../classExaDG_1_1SmootherBase.html',1,'ExaDG']]],
  ['smootherbase_3c_20vectortypemg_20_3e_6',['SmootherBase&lt; VectorTypeMG &gt;',['../classExaDG_1_1SmootherBase.html',1,'ExaDG']]],
  ['smootherdata_7',['SmootherData',['../structExaDG_1_1SmootherData.html',1,'ExaDG']]],
  ['solutionfield_8',['SolutionField',['../classExaDG_1_1SolutionField.html',1,'ExaDG']]],
  ['solutioninterpolationbetweentriangulations_9',['SolutionInterpolationBetweenTriangulations',['../classExaDG_1_1SolutionInterpolationBetweenTriangulations.html',1,'ExaDG']]],
  ['solutiontransfer_10',['SolutionTransfer',['../classExaDG_1_1SolutionTransfer.html',1,'ExaDG']]],
  ['solver_11',['Solver',['../classExaDG_1_1IncNS_1_1Precursor_1_1Solver.html',1,'ExaDG::IncNS::Precursor::Solver&lt; dim, Number &gt;'],['../classExaDG_1_1Newton_1_1Solver.html',1,'ExaDG::Newton::Solver&lt; VectorType, NonlinearOperator, LinearOperator, LinearSolver &gt;'],['../classExaDG_1_1Poisson_1_1OversetGrids_1_1Solver.html',1,'ExaDG::Poisson::OversetGrids::Solver&lt; dim, n_components, Number &gt;']]],
  ['solver_3c_20vectortype_2c_20residualoperator_3c_20dim_2c_20number_20_3e_2c_20linearizedoperator_3c_20dim_2c_20number_20_3e_2c_20krylov_3a_3asolverbase_3c_20vectortype_20_3e_20_3e_12',['Solver&lt; VectorType, ResidualOperator&lt; dim, Number &gt;, LinearizedOperator&lt; dim, Number &gt;, Krylov::SolverBase&lt; VectorType &gt; &gt;',['../classExaDG_1_1Newton_1_1Solver.html',1,'ExaDG::Newton']]],
  ['solveracoustic_13',['SolverAcoustic',['../classExaDG_1_1AeroAcoustic_1_1SolverAcoustic.html',1,'ExaDG::AeroAcoustic']]],
  ['solverbase_14',['SolverBase',['../classExaDG_1_1Elementwise_1_1SolverBase.html',1,'ExaDG::Elementwise::SolverBase&lt; value_type, Matrix, Preconditioner &gt;'],['../classExaDG_1_1Krylov_1_1SolverBase.html',1,'ExaDG::Krylov::SolverBase&lt; VectorType &gt;']]],
  ['solverbase_3c_20dealii_3a_3alinearalgebra_3a_3adistributed_3a_3avector_3c_20number_20_3e_20_3e_15',['SolverBase&lt; dealii::LinearAlgebra::distributed::Vector&lt; Number &gt; &gt;',['../classExaDG_1_1Krylov_1_1SolverBase.html',1,'ExaDG::Krylov']]],
  ['solvercg_16',['SolverCG',['../classExaDG_1_1Elementwise_1_1SolverCG.html',1,'ExaDG::Elementwise::SolverCG&lt; value_type, Matrix, Preconditioner &gt;'],['../classExaDG_1_1Krylov_1_1SolverCG.html',1,'ExaDG::Krylov::SolverCG&lt; Operator, Preconditioner, VectorType &gt;']]],
  ['solverdata_17',['SolverData',['../structExaDG_1_1Newton_1_1SolverData.html',1,'ExaDG::Newton::SolverData'],['../structExaDG_1_1SolverData.html',1,'ExaDG::SolverData']]],
  ['solverdatacg_18',['SolverDataCG',['../structExaDG_1_1Krylov_1_1SolverDataCG.html',1,'ExaDG::Krylov']]],
  ['solverdatafgmres_19',['SolverDataFGMRES',['../structExaDG_1_1Krylov_1_1SolverDataFGMRES.html',1,'ExaDG::Krylov']]],
  ['solverdatagmres_20',['SolverDataGMRES',['../structExaDG_1_1Krylov_1_1SolverDataGMRES.html',1,'ExaDG::Krylov']]],
  ['solverfgmres_21',['SolverFGMRES',['../classExaDG_1_1Krylov_1_1SolverFGMRES.html',1,'ExaDG::Krylov']]],
  ['solverfluid_22',['SolverFluid',['../classExaDG_1_1AeroAcoustic_1_1SolverFluid.html',1,'ExaDG::AeroAcoustic::SolverFluid&lt; dim, Number &gt;'],['../classExaDG_1_1FSI_1_1SolverFluid.html',1,'ExaDG::FSI::SolverFluid&lt; dim, Number &gt;']]],
  ['solvergmres_23',['SolverGMRES',['../classExaDG_1_1Elementwise_1_1SolverGMRES.html',1,'ExaDG::Elementwise::SolverGMRES&lt; value_type, Matrix, Preconditioner &gt;'],['../classExaDG_1_1Krylov_1_1SolverGMRES.html',1,'ExaDG::Krylov::SolverGMRES&lt; Operator, Preconditioner, VectorType &gt;']]],
  ['solverinfodata_24',['SolverInfoData',['../structExaDG_1_1SolverInfoData.html',1,'ExaDG']]],
  ['solverresult_25',['SolverResult',['../structExaDG_1_1SolverResult.html',1,'ExaDG']]],
  ['solverstructure_26',['SolverStructure',['../classExaDG_1_1FSI_1_1SolverStructure.html',1,'ExaDG::FSI']]],
  ['soundenergycalculator_27',['SoundEnergyCalculator',['../classExaDG_1_1Acoustics_1_1SoundEnergyCalculator.html',1,'ExaDG::Acoustics']]],
  ['soundenergycalculatordata_28',['SoundEnergyCalculatorData',['../structExaDG_1_1Acoustics_1_1SoundEnergyCalculatorData.html',1,'ExaDG::Acoustics']]],
  ['sourcetermcalculator_29',['SourceTermCalculator',['../classExaDG_1_1AeroAcoustic_1_1SourceTermCalculator.html',1,'ExaDG::AeroAcoustic']]],
  ['sourcetermcalculatordata_30',['SourceTermCalculatorData',['../structExaDG_1_1AeroAcoustic_1_1SourceTermCalculatorData.html',1,'ExaDG::AeroAcoustic']]],
  ['spatialawarefunction_31',['SpatialAwareFunction',['../classExaDG_1_1Utilities_1_1SpatialAwareFunction.html',1,'ExaDG::Utilities']]],
  ['spatialoperator_32',['SpatialOperator',['../classExaDG_1_1Acoustics_1_1Interface_1_1SpatialOperator.html',1,'ExaDG::Acoustics::Interface::SpatialOperator&lt; Number &gt;'],['../classExaDG_1_1Acoustics_1_1SpatialOperator.html',1,'ExaDG::Acoustics::SpatialOperator&lt; dim, Number &gt;']]],
  ['spatialoperatorbase_33',['SpatialOperatorBase',['../classExaDG_1_1Acoustics_1_1SpatialOperatorBase.html',1,'ExaDG::Acoustics::SpatialOperatorBase&lt; dim, Number &gt;'],['../classExaDG_1_1IncNS_1_1SpatialOperatorBase.html',1,'ExaDG::IncNS::SpatialOperatorBase&lt; dim, Number &gt;']]],
  ['spatialoperatorbase_3c_20dim_2c_20double_20_3e_34',['SpatialOperatorBase&lt; dim, double &gt;',['../classExaDG_1_1IncNS_1_1SpatialOperatorBase.html',1,'ExaDG::IncNS']]],
  ['spatialresolutionparameters_35',['SpatialResolutionParameters',['../structExaDG_1_1SpatialResolutionParameters.html',1,'ExaDG']]],
  ['spatialresolutionparametersminmax_36',['SpatialResolutionParametersMinMax',['../structExaDG_1_1SpatialResolutionParametersMinMax.html',1,'ExaDG']]],
  ['spectralanalysis_37',['SpectralAnalysis',['../classdealspectrum_1_1SpectralAnalysis.html',1,'dealspectrum']]],
  ['ssprk_38',['SSPRK',['../classExaDG_1_1SSPRK.html',1,'ExaDG']]],
  ['statisticsmanager_39',['StatisticsManager',['../classExaDG_1_1StatisticsManager.html',1,'ExaDG']]],
  ['streamfunctioncalculatorrhsoperator_40',['StreamfunctionCalculatorRHSOperator',['../classExaDG_1_1IncNS_1_1StreamfunctionCalculatorRHSOperator.html',1,'ExaDG::IncNS']]],
  ['stvenantkirchhoff_41',['StVenantKirchhoff',['../classExaDG_1_1Structure_1_1StVenantKirchhoff.html',1,'ExaDG::Structure']]],
  ['stvenantkirchhoffdata_42',['StVenantKirchhoffData',['../structExaDG_1_1Structure_1_1StVenantKirchhoffData.html',1,'ExaDG::Structure']]],
  ['symmetric_5ftensor_43',['symmetric_tensor',['../classExaDG_1_1Structure_1_1Material.html',1,'ExaDG::Structure']]]
];
