MACRO(PRINT_EXADG_HEADER)

MESSAGE("________________________________________________________________________________")
MESSAGE("                                                                                ")
MESSAGE("                ////////                      ///////   ////////                ")
MESSAGE("                ///                           ///  ///  ///                     ")
MESSAGE("                //////    ///  ///  ///////   ///  ///  /// ////                ")
MESSAGE("                ///         ////    //   //   ///  ///  ///  ///                ")
MESSAGE("                ////////  ///  ///  ///////// ///////   ////////                ")
MESSAGE("                                                                                ")
MESSAGE("               High-Order Discontinuous Galerkin for the Exa-Scale              ")
MESSAGE("________________________________________________________________________________")
MESSAGE("                                                                                ")

ENDMACRO(PRINT_EXADG_HEADER)
