MACRO(EXADG_PICKUP_TESTS TARGET_NAME)

  IF( NOT "${NUMDIFF_EXECUTABLE}" MATCHES "NUMDIFF_EXECUTABLE-NOTFOUND")
    DEAL_II_PICKUP_TESTS(TARGET_NAME)
  ENDIF() 

ENDMACRO(EXADG_PICKUP_TESTS)

MACRO(EXADG_PICKUP_TESTS)

  IF( NOT "${NUMDIFF_EXECUTABLE}" MATCHES "NUMDIFF_EXECUTABLE-NOTFOUND")
    DEAL_II_PICKUP_TESTS()
  ENDIF() 

ENDMACRO(EXADG_PICKUP_TESTS)
