MACRO(EXADG_PICKUP_TESTS TARGET_NAME)

  IF(${PICKUP_TESTS})
    DEAL_II_PICKUP_TESTS(TARGET_NAME)
  ENDIF() 

ENDMACRO(EXADG_PICKUP_TESTS)

MACRO(EXADG_PICKUP_TESTS)

  IF(${PICKUP_TESTS})
    DEAL_II_PICKUP_TESTS()
  ENDIF() 

ENDMACRO(EXADG_PICKUP_TESTS)
