#!/bin/sh
#########################################################################
# 
#                 #######               ######  #######
#                 ##                    ##   ## ##
#                 #####   ##  ## #####  ##   ## ## ####
#                 ##       ####  ## ##  ##   ## ##   ##
#                 ####### ##  ## ###### ######  #######
#
#  ExaDG - High-Order Discontinuous Galerkin for the Exa-Scale
#
#  Copyright (C) 2021 by the ExaDG authors
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#########################################################################

if test -f "contrib/utilities/programs/clang-11/bin/clang-format"; then
  cf=contrib/utilities/programs/clang-11/bin/clang-format
else
  cf=clang-format
fi

# print which clang-format is used
echo $cf
$cf --version

# format header files
for i in $(find . -type f \( -name "*.h" -o -name "*.h.in" -o -name "*.cc" -o -name "*.cpp" \) ); do 
  $cf -i $i
done
