#!/bin/sh
#########################################################################
# 
#                 #######               ######  #######
#                 ##                    ##   ## ##
#                 #####   ##  ## #####  ##   ## ## ####
#                 ##       ####  ## ##  ##   ## ##   ##
#                 ####### ##  ## ###### ######  #######
#
#  ExaDG - High-Order Discontinuous Galerkin for the Exa-Scale
#
#  Copyright (C) 2021 by the ExaDG authors
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#########################################################################

SEARCH_STRING=$1
REPLACE_STRING=$2

echo "replace " $SEARCH_STRING " by " $REPLACE_STRING " in all files"

# loop over all files, and replace SEARCH_STRING by REPLACE_STRING
for i in $(find . -type f \( -name "*.h" -o -name "*.h.in" -o -name "*.cc" -o -name "*.cpp" \) ); do 
  sed -i "s/$SEARCH_STRING/$REPLACE_STRING/" $i
done