#!/bin/bash
#########################################################################
# 
#                 #######               ######  #######
#                 ##                    ##   ## ##
#                 #####   ##  ## #####  ##   ## ## ####
#                 ##       ####  ## ##  ##   ## ##   ##
#                 ####### ##  ## ###### ######  #######
#
#  ExaDG - High-Order Discontinuous Galerkin for the Exa-Scale
#
#  Copyright (C) 2021 by the ExaDG authors
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#########################################################################

set -e

# make sure that parameters are understood correctly
if [ "$1" == "-np" ]; then
    NPROCS=$2
else
    echo -e "\nUse the following syntax:\n\n./makempirun -np [NPROCS] [EXE]\n"
    exit 0
fi

if [ "$3" == "" ]; then
    echo -e "\nUse the following syntax:\n\n./makempirun -np [NPROCS] [EXE]\n"
    exit 0
fi

EXE=$3

# build the executable
echo -e "make -j1 $EXE\n"
make $EXE

# run the executable
mpirun -np $NPROCS $EXE
